name: customer_app
version: 1.0.14+17
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+4
  # firebase_utils: ^1.0.1
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  image_picker: ^1.0.7
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^28.2.11
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  # flutter_share: ^2.0.0
  clipboard: ^0.1.3
  geolocator:
  lottie: ^3.1.2
  geocoding: ^3.0.0
  flutter_svg: ^2.0.7
  # geoflutterfire2: ^2.3.15
  google_sign_in: ^6.2.1
  uuid: ^4.1.0
  dotted_border: ^2.1.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  url_launcher: ^6.1.14
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  cron: ^0.6.0
  # alarm: ^4.1.1
  # qr_code_scanner: ^1.0.1
  get_storage: ^2.0.2
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  sliding_switch: ^1.1.0
  flutter_flavor: ^3.1.1
  google_fonts: ^6.2.1
  badges: ^3.1.2

  #payment_dependencies
  # flutter_stripe: ^11.0.0
  # flutter_paypal_native: ^2.1.0

  flutter:
    sdk: flutter
  skeletonizer: ^1.1.1
  custom_sliding_segmented_control: ^1.8.1
  flutter_image_compress: ^2.2.0
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
  webview_flutter: ^4.7.0
  # flutter_datetime_picker: ^1.5.1
  calendar_date_picker2: ^1.0.3
  package_info_plus: ^8.0.1
  pdf: ^3.11.0
  share_plus: ^10.0.0
  path_provider: ^2.1.3
  mobile_scanner: ^7.0.1
  syncfusion_flutter_core: ^28.2.11
  infinite_scroll_pagination: ^4.0.1
  qr_code_scanner_plus: ^2.0.10+1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf

    - family: Figtree-Medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/gif/
